### ISSUE TITLE
Meta scope shouldn't share same base colour as comments

### ISSUE THREAD

**Issue by Alhadis** [simurai/duotone-syntax#17]
I don't know how much this affects better-known languages, but I've noticed the `meta` scope is used by DuoTone to apply text colour (assuming when nothing more specific matches):

<img src="https://cloud.githubusercontent.com/assets/2346707/17104582/da519b64-52c6-11e6-9f1c-dd1a79ccf084.png" width="733" alt="Figure 1" />

Generally, this isn't a very good idea, as the `meta` scope is [typically used](http://manual.macromates.com/en/language_grammars#footer) for identifying larger regions of a document (often for programmatic purposes, such as triggering a certain snippet or what-have-you). This should probably just inherit the default colour used for ordinary text.

**Comment by simurai** [comment]
I'll have to take a closer look again, but as far as I remember, coloring `meta` was added because certain things like punctuation weren't scoped in all languages. So meta was used as a "catch all" hack. Maybe it can be removed again if language packages added enough support.

**Comment by Alhadis** [comment]
@simurai You might consider targeting `meta.brace` instead then, as that appears to be the name (wrongly) used by some packages for marking up brackets. Targeting `meta` itself is inviting disaster.

**Comment by simurai** [comment]
> You might consider targeting `meta.brace` instead

Yeah, or if really necessary, limit to certain languages e.g. `.meta.js` and not as wildcard.

**Comment by Alhadis** [comment]
Isn't there already language-specific styling for JS, though?

**Comment by Alhadis** [comment]
@simurai This is still an issue, and it's quite a glaring one. I'd hoped it'd be fixed by a major release.

**Comment by simurai** [comment]
@Alhadis On it.. 👍

**Comment by Alhadis** [comment]
Holy shit, THANK YOU.
