### ISSUE TITLE
Subduing comment tag tones?

### ISSUE THREAD

**Issue by objectkit** [simurai/duotone-syntax#26]
Hi there. I really love this. Is there a way to subdue comment tags? They are presently showing with the same luminescence as keywords.  The comment rule subdues plain text in comments, but being able to subdue comment tags more than keywords would give much better separation between heavy documentation and implementation code. I've read through, but the means has escaped me. Is this a feature that has already been implemented or am I missing something? I probably am as my CSS skills are close to none. Danke!

**Comment by simurai** [comment]
Hi. What do you mean by "comment tags"? Mind posting a screenshot, code sample and what language it is?

Comments already should look very subtle and less strong than keywords.

**Comment by objectkit** [comment]
Hi there! Thanks for getting back to me. doc comment @tags...
![vectorsyntaxduotone](https://cloud.githubusercontent.com/assets/1374645/25964095/983c973a-367b-11e7-9a8b-ac8085f325be.png)

![vectorsyntaxcoffee](https://cloud.githubusercontent.com/assets/1374645/25964840/26af5c3a-367e-11e7-8e3d-e82690a6e237.png)
This is a screenshot of [Vector-Syntax](https://github.com/nkpfstr/vector-syntax) in action. Its a fork, so I assume this is also how duo-tone presents comment tags. I would have assumed comment tags to have been a lighter shade?

**Comment by simurai** [comment]
I see. Yes, that doesn't look right. I'll try if I can reproduce it. Thanks for notifying.

**Comment by objectkit** [comment]
Relieved you agree! Not a problem. Many thanks to you. Looking forward to your findings . DuoTone is otherwise perfect!

**Comment by objectkit** [comment]
Hi @simurai, just wondering if you've been able to reproduce it?

**Update**
I've just noticed that you have released [tone-syntax](https://github.com/simurai/tone-syntax). Its looking good! I have been able to emulate Vector-Syntax to some degree. At first, there seemed to be a bug (background discolouration)...

![tone-syntax -bug](https://cloud.githubusercontent.com/assets/1374645/26629386/0f81bfa4-45fa-11e7-9daa-fa9dc1bf37eb.png)

So I switched back to Vector

![vector](https://cloud.githubusercontent.com/assets/1374645/26629397/1d3ccc56-45fa-11e7-8ffb-3ba35604402b.png)

Then back to tone-syntax... and it seemed to iron out.

![tone-syntax-fixed](https://cloud.githubusercontent.com/assets/1374645/26629408/2b03f53a-45fa-11e7-8bcd-c47e336108c8.png)

I think this issue can be closed. Thanks for the new theme. Onwards to [tone-syntax](https://github.com/simurai/tone-syntax)!

**Comment by simurai** [comment]
> there seemed to be a bug

Hmm.. yeah, looks like something didn't get reloaded. Also if you make changes in tone-syntax you have to click the "Sync UI" checkbox so that other packages update too.

**Comment by objectkit** [comment]
> click the "Sync UI" checkbox so that other packages update too

Thanks for the info. I'll keep an eye out for that! 

I would like to investigate what would be needed to contribute towards javascript language support in tone-syntax. I haven't touched less in a number of years so I am likely unqualified. Could you suggest any resources demonstrating how one would go about implementing language support in conjunction with Atom's styles? Is that even the correct view to have? 

For example, my attempt to emulate Vector with tone-syntax didn't stylise the ``class`` keyword:

![tone-syntax-class-keyword](https://cloud.githubusercontent.com/assets/1374645/26698147/a390f698-470c-11e7-8a25-ea9ed7e118d1.jpg)

I assume this is because [language maintainers](https://github.com/simurai/tone-syntax#un-maintained-languages) for javascript are presently needed for tone-syntax. I'm unsure if I am up to the task, but out of interest, I took a peek with chrome inspector:

![tone-syntax-js-css](https://cloud.githubusercontent.com/assets/1374645/26698161/b66fe1de-470c-11e7-8cd9-811b5e2460de.jpg)

I didn't see any way obvious way to introduce the ``class`` keyword into tone-syntax styles/languages/javascript.less...  even though I noticed the ``syntax--storage.syntax--type.syntax--class.syntax--js`` ruleset... but no clear idea of how to introduce that (or even if I should introduce that) into javascript.less.

A quick heads up would be great if its convenient, and its no problem to move this question over to tone-syntax if that is a more appropriate location. Many thanks @simurai
