### ISSUE TITLE
 GF Markdown could use a little bump

### ISSUE THREAD

**Issue by huphtur** [simurai/duotone-syntax#4]
GF Markdown sans (supported) language identifier seem a tad too dark at times?

![darkspace](https://cloud.githubusercontent.com/assets/469438/12073833/cef186ec-b133-11e5-9dc0-a0d9cbc1963a.png)

![darksea](https://cloud.githubusercontent.com/assets/469438/12073834/d428e394-b133-11e5-968b-f4a89a74189b.png)

**Comment by simurai** [comment]
I see.. inline and fenced code is indeed a bit weak. How about this:

![screen shot 2016-01-04 at 4 57 25 pm](https://cloud.githubusercontent.com/assets/378023/12085528/3fd44d0a-b304-11e5-8f54-cf174904f1bc.png)

Strong raw markup, but weak back ticks.

**Comment by huphtur** [comment]
:+1:
