### ISSUE TITLE
Sublime Text Support

### ISSUE THREAD

**Issue by rafegoldberg** [simurai/duotone-syntax#8]
These look beautiful. Any chance they'll be released for Sublime Text? Or do they work out of the box (I vaguely remember hearing that syntax themes are cross-compatible somewhere...) Thanks!

**Comment by simurai** [comment]
There is https://github.com/atelierbram/syntax-highlighting/tree/master/duotones/output/textmate.

It was ported with the base16-builder, so it might not match exactly since DuoTone has fewer colors and maybe different logic. But maybe close.

**Comment by rafegoldberg** [comment]
You're awesome. These themes look awesome. I'll check it out. Thanks!
